GET http://localhost:4000/

###

GET  http://localhost:4000/api/todos

###


GET  http://localhost:4000/api/todobyid/5f7775c844f1124000f47383
###

DELETE http://localhost:4000/api/delete/5f762ac3ea9e843bb8fd7084

###

POST http://localhost:4000/api/create
content-type: application/json

{
    "title": "do van hack videos",
    "isCompleted": false
}

###
PUT http://localhost:4000/api/update/5f762ac3ea9e843bb8fd7084
content-type: application/json

{
    "id": "5f762ac3ea9e843bb8fd7084",
    "title": "walk the dog",
    "isCompleted": false
}


